apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: gathering-leto
spec:
  environments:
    - name: development
      build:
        from: master
    - name: production
      build:
        from: release
  components:
    - name: server
      src: "."
      ports:
       - name: http
         port: 8000
      publicPort: http
  dnsAppAlias:
    environment: production
    component: server
