# This workflow will install Python dependencies and run unit tests

name: unit_tests

on:
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ master, release ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - uses: "actions/setup-python@v2"
      with:
        python-version: "${{ matrix.python-version }}"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install development dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f dev_requirements.txt ]; then pip install -r dev_requirements.txt; fi
    - name: Install data module
      run: |
        python -m pip install --upgrade pip
        pip install src/data
    - name: Run pytest
      run: |
        pytest tests
